### ISSUE TITLE
Card blinking

### ISSUE THREAD

**Issue by darkkatarsis** [custom-cards/config-template-card#15]
I noticed a strange behavior of the card. Every few seconds you can see that data inside card were refreshed. It is worth noting that this effect is not present when the graph card is outside "custom: config-template-card"

Code:

`- type: 'custom:config-template-card'
        card:
          type: 'custom:mini-graph-card'
          entities:
            - sensor.bedroom_temperature
          line_color: "${ states['sensor.bedroom_temperature'].state <= 20 ? '#2980b9' : ( states['sensor.bedroom_temperature'].state <= 22 ? '#b58e31' : '#b93829' ) }"
          line_width: 4
          name: Test`

![blink](https://user-images.githubusercontent.com/24244919/64047268-9b120000-cb6e-11e9-9121-294eb4bb4ad6.gif)

**Comment by iantrich** [comment]
Add your entities to the `entities` list so that it does not update so often

**Comment by darkkatarsis** [comment]
Now working just fine! thank you
