### ISSUE TITLE
License difference?

### ISSUE THREAD

**Issue by brianhanifin** [custom-cards/config-template-card#5]
I noticed two difference licenses referenced. [/LICENSE](https://github.com/custom-cards/config-template-card/blob/master/LICENSE) is an MIT License. While the header of [/dist/config-template-card.js](https://github.com/custom-cards/config-template-card/blob/master/dist/config-template-card.js) references the Apache License (and copyright Microsoft?). I am no expert in this, but I wanted to share it with you in case it was unintentional.

**Comment by iantrich** [comment]
Neither am I :) but the resulting .js file is a rollup of my code and all dependencies, so likely one of the dependencies got their license info bundled in the final file 🤷‍♂️
