### ISSUE TITLE
Cannot click on entities (i.e., more info not working)

### ISSUE THREAD

**Issue by arsaboo** [custom-cards/config-template-card#7]
So, after adding the template cards, we are not able to click the entities to open the more-info cards.

**Comment by iantrich** [comment]
I can’t replicate that. Please provide installation/environment/browser details

**Comment by arsaboo** [comment]
Ubuntu venv. Browser Chrome

**Comment by arsaboo** [comment]
It looks like it may be due to combining template card with card-modder. Here's my card config https://github.com/arsaboo/homeassistant-config/blob/master/ui-lovelace.yaml#L1114

**Comment by arsaboo** [comment]
Closing in favor of https://github.com/thomasloven/lovelace-card-modder/issues/31
